example:
  api:
    url: https://default.example.example
    exampleValue: exampleDefaultValue

spring:
  config:
    import: "optional:file:.env[.properties]"

gemini:
  version: "gemini-3-flash-preview"

spring.config.activate.on-profile: local

---
spring.config.activate.on-profile:
  - local-dev
  - dev
---
spring.config.activate.on-profile:
  - staging
  - live
---


